name: Build and publish to main/docs

on:
  push:
    branches: [ main ]
    # Prevent workflow from running on its own commits to the docs/ folder
    paths-ignore:
      - 'docs/**'
  workflow_dispatch: {}

permissions:
  contents: write # Required to commit to the repository
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Copy build output to docs/
        run: |
          rm -rf docs
          mkdir -p docs
          cp -a dist/. docs/
          # Create a .nojekyll file to disable Jekyll processing by GitHub Pages
          touch docs/.nojekyll

      - name: Commit and push docs/ to main
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add docs
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "docs: Update site build [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
